### PR TITLE
Add posibility for widescreen PPTX

### PR DESCRIPTION
**Pull request by Trekky12**
This PR adds the possibility to create a widescreen PPTX

### CODE REVIEW

**Comment by aumouvantsillage** [comment]
Thanks for submitting this pull request.

Please note that Sozi-export will be deprecated soon.
PDF, PPTX and video export have been successfully integrated into the main presentation editor, and I hope to publish a test release in a few days.
I believe Sozi-export will no longer be relevant as a separate tool.

BTW when exporting to PPTX from Sozi, a widescreen option will be available

**Comment by aumouvantsillage** [comment]
For your information, I have finally decided to publish the test release today. If you are interested in testing the export features, you can find it here: https://github.com/sozi-projects/Sozi/releases/tag/v20.10-beta

**Comment by Trekky12** [comment]
Thank you for this information and the pre-release 👍 
I just noticed that the widescreen export is already included, but unfortunately after the export and generation of the pptx the loading icon on the export button is still shown:
grafik

**Comment by aumouvantsillage** [comment]
@Trekky12 Can you report this issue at https://github.com/sozi-projects/Sozi/issues ?

If you can reproduce the problem, it would be great if you could open the developer tools (by pressing F12) and check the "Console" tab for error messages.
Thanks.

**Pull request merged**
